services:
  dnas_redis:
    container_name: dnas_redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/dnas/redis/data:/data
      - /opt/dnas/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    tty: true
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  dnas_getter:
    container_name: dnas_getter
    image: dnas:latest
    build:
      args:
        - PYPY=$PYPY
      context: /opt/dnas/
      dockerfile: docker/dnas.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/opt/dnas/:z
      - /opt/dnas_data/:/opt/dnas_data/
    restart: always
    tty: true
    depends_on:
      - dnas_redis
    command:
      - /opt/dnas/dnas/scripts/get_mrts.py
      - --continuous
      - --update
      - --enabled

  dnas_parser:
    container_name: dnas_parser
    image: dnas:latest
    build:
      args:
        - PYPY=$PYPY
      context: /opt/dnas/
      dockerfile: docker/dnas.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/opt/dnas/:z
      - /opt/dnas_data/:/opt/dnas_data/
    restart: always
    tty: true
    depends_on:
      - dnas_redis
    command:
      - /opt/dnas/dnas/scripts/parse_mrts.py
      - --continuous
      - --update
      - --enabled
      - --remove

  dnas_stats:
    container_name: dnas_stats
    image: dnas:latest
    build:
      args:
        - PYPY=$PYPY
      context: /opt/dnas/
      dockerfile: docker/dnas.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - ../:/opt/dnas/:z
      - /opt/dnas_data/:/opt/dnas_data/
    restart: always
    tty: true
    depends_on:
      - dnas_redis
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    entrypoint:
      - /usr/sbin/cron
      - -f

