version: "3.9"

services:
  dnas_redis:
    container_name: dnas_redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/dnas/redis/data:/data
      - /opt/dnas/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    tty: true
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  dnas_getter:
    container_name: dnas_getter
    image: dnas:latest
    build:
      context: /opt/dnas/
      dockerfile: docker/dnas.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - /media/usb0/:/media/usb0/
    restart: always
    tty: true
    depends_on:
      - dnas_redis
    entrypoint:
      - /opt/pypy3.8-v7.3.7-aarch64/bin/pypy3
      - /opt/dnas/scripts/get_mrts.py
      - --continuous
      - --update

  dnas_parser:
    container_name: dnas_parser
    image: dnas:latest
    build:
      context: /opt/dnas/
      dockerfile: docker/dnas.Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - /media/usb0/:/media/usb0/
    restart: always
    tty: true
    depends_on:
      - dnas_redis
    entrypoint:
      - /opt/pypy3.8-v7.3.7-aarch64/bin/pypy3
      - /opt/dnas/scripts/parse_mrts.py
      - --continuous
      - --update
      - --remove

