name: python-unit-tests
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

jobs:
  python-unit-tests:
    name: Python Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dnas/requirements.txt
      - name: Run the Python unit tests
        working-directory: /home/runner/work/dfz_name_and_shame/dfz_name_and_shame/
        #sudo /opt/hostedtoolcache/Python/3.8.12/x64/bin/pytest
        run: |
          python3 dnas/tests/test_bogon_asn.py -v
          python3 dnas/tests/test_bogon_ip.py -v
          sudo python3 dnas/tests/test_git.py -v
          python3 dnas/tests/test_mrt_archive.py -v
          python3 dnas/tests/test_mrt_entry.py -v
          python3 dnas/tests/test_mrt_getter.py -v
          python3 dnas/tests/test_mrt_parser.py -v
          python3 dnas/tests/test_mrt_splitter.py -v
          python3 dnas/tests/test_mrt_stats.py -v
