name: python-unit-tests
on:
  push:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

jobs:
  python-unit-tests:
    name: Python Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dnas/requirements.txt
      - name: Run the Python unit tests
        #working-directory: ./dnas/
        run: |
          sudo /opt/hostedtoolcache/Python/3.8.12/x64/bin/pytest
