name: python-unit-tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  python-unit-tests:
    name: Python Unit Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_ACTION_SSH_PRIV_KEY }}
      - name: Setup git
        run: |
          git config --global user.email "github_actions@example.com"
          git config --global user.name "Github Actions"
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dnas/requirements.txt
          sudo apt-get install -y whois shellcheck
      - name: Run the tox tests
        working-directory: /home/runner/work/dfz_name_and_shame/dfz_name_and_shame/
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            tox
